### ISSUE TITLE
Better inputs for the caffe_image_classify docker

### ISSUE THREAD

**Issue by elboyran** [nlesc-sherlock/deeplearning#25]
Classifying multiple images by giving all their names file by file doesn't seem convenient.

The input should be:
- single images
- directory with (jpg or png) images
- list of image locations

**Comment by egpbos** [comment]
I agree that all those options are convenient, we should add them.

However, in Unix commands, it is very common to specify input by giving multiple file names (with wildcards, of course, like `image*.jpg` instead of typing it out yourself like `image1.jpg image2.jpg ... imageN.jpg`; the shell automatically expands the wildcard version to the latter version), so this option should stay as well, I think.

The way it is implemented now is very crappy, though (having to prepend the internal docker location), so we should definitely change that. Two possibilities for that are:
1. Wrap the `docker run` command in yet another (Bash) script (the Docker itself is already a wrapper around the `cnn_classify.py` script). This makes it Bash-dependent and, effectively, Linux/OSX-dependent, excluding Windows users. Do we care about that?
2. Try to find out a nice way to pass arguments to Docker in such a way that we can transform them before passing them to the Python script inside the container.

**Comment by elboyran** [comment]
DIGITS allows us to specify list of filenames (generated by ls > list.txt). Since we'll prepare few for demo purposes, we should have the same input option and show it works with this same input also from the command line.

**Comment by egpbos** [comment]
Ok, so subtasks:
- [ ] Add _filename list txt-file_ parameter
- [ ] Fix multiple filename option
- [ ] Add _directory with images_ parameter (problems: which images in the directory? should it be directory with only images? which filetypes, jpg only or also png? does caffe handle multiple formats?)

Giving a single filename is already possible.

**Comment by egpbos** [comment]
I just now remembered from previous sprint that one of the problems I had was passing in wildcards like `*`, `?`, `[0-9]` or `{foo,bar}` as arguments to the Docker container. They either expand in the host shell or they are passed literally to the container and are not expanded there either. Need help from Docker guru.

**Comment by egpbos** [comment]
Another problem is how exposing host-files to the container works in Docker (i.e. like crap). If we can come up with a more general way of passing in files to Docker containers, I think we will save the world. Perhaps the integration team has some ideas?

**Comment by egpbos** [comment]
Solution to the "prepending internal Docker location" problem: use two Docker containers.

Container 1: call the Python script with a special flag that indicates that the given image file paths are host-local. The Python script will then transform them to container-local paths and run the next container.

Container 2: the current container.

**Comment by elboyran** [comment]
Nice.

Sent from Samsung Mobile

-------- Original message --------
From: Patrick Bos
Date:18/02/2016 13:01 (GMT+01:00)
To: nlesc-sherlock/deeplearning
Cc: Elena Ranguelova
Subject: Re: [deeplearning] Better inputs for the caffe_image_classify docker (#25)

Solution to the "prepending internal Docker location" problem: use two Docker containers.

Container 1: call the Python script with a special flag that indicates that the given image file paths are host-local. The Python script will then transform them to container-local paths and run the next container.

Container 2: the current container.

##

**Comment by egpbos** [comment]
We can also just solve the image-list file case with a terminal command like:

```
docker run [options] $(paste filenames.txt)
```

**Comment by egpbos** [comment]
We didn't implement the docker-in-docker idea after all. @bpmweel added a data directory option and changed the file input method.

For future reference, if we still want to implement docker-in-docker, this may be useful: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
