### ISSUE TITLE
Use deepvis toolbox

### ISSUE THREAD

**Issue by Maartenvm** [nlesc-sherlock/deeplearning#32]
To visualize and explain what the network is doing.

https://github.com/yosinski/deep-visualization-toolbox

**Comment by egpbos** [comment]
Wow, we should definitely try this...

**Comment by cwmeijer** [comment]
Yes, this could be a very nice thing to try in the next sprint.

Video of the same tool:

**Comment by cwmeijer** [comment]
mail got sent early because of weird shortkeys in outlook [&#X02639]

here's the link anyway:

https://www.youtube.com/watch?v=AgkfIQ4IGaM

[http://tse2.mm.bing.net/th?id=OVP.Vb0862d1cdcedf014f7e5951a2d3e8a5f&w=250&h=140&c=7&pid=Api]https://www.youtube.com/watch?v=AgkfIQ4IGaM

Deep Visualization Toolboxhttps://www.youtube.com/watch?v=AgkfIQ4IGaM
www.youtube.com
Code and more info: http://yosinski.com/deepvis

**Comment by elboyran** [comment]
Yes, we should!
