### ISSUE TITLE
Obtain imagenet dataset for fine-tuning

### ISSUE THREAD

**Issue by egpbos** [nlesc-sherlock/deeplearning#45]
Ask Valeriu at SURFsara.

**Comment by egpbos** [comment]
Lykle is putting the data on a ceph disk. He will transfer ownership of it to my account (once our sherlock group quota is set high enough) so I can hook it up to our HPC cloud VM.

**Comment by elboyran** [comment]
Valeriu is on holiday until 23 May. Didn't Berend get access to Imagenet already?

**Comment by egpbos** [comment]
Yep, but Jason told us that SURFsara also had a copy lying around (on Cartesius). They now copied it to a HPC Cloud ceph image, so that we can also use it from the HPC cloud. That saves us another lengthy copy, and it was not a lot of work anyway, since Lykle and Jeroen took care of it for us :) Win win.

They finished copying and I have it attached to the VM now.

By the way, would it be useful if I put my sherlock-patrickb account in Lastpass so we can all access it? I don't mind administrating the VM, but perhaps other people would like to fiddle with it. Let me know.

**Comment by elboyran** [comment]
I guess it's useful to share your account.

Sent from Samsung Mobile

-------- Original message --------
From: Patrick Bos
Date:11/05/2016 07:06 (GMT+01:00)
To: nlesc-sherlock/deeplearning
Cc: Elena Ranguelova , Comment
Subject: Re: [nlesc-sherlock/deeplearning] Obtain imagenet dataset for fine-tuning (#45)

Yep, but Jason told us that SURFsara also had a copy lying around (on Cartesius). They now copied it to a HPC Cloud ceph image, so that we can also use it from the HPC cloud. That saves us another lengthy copy, and it was not a lot of work anyway, since Lylke and Jeroen took care of it for us :) Win win.

They finished copying and I have it attached to the VM now.

By the way, would it be useful if I put my sherlock-patrickb account in Lastpass so we can all access it? I don't mind administrating the VM, but perhaps other people would like to fiddle with it. Let me know.

##
